name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
  workflow_call:

jobs:
#   yarn-lockfile-check:
#     uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
#   Since the Windows unit tests take much longer, we run the linux unit tests first and then run the windows unit tests in parallel with NUTs
#   linux-unit-tests:
#     needs: yarn-lockfile-check
#     uses: salesforcecli/github-workflows/.github/workflows/unitTestsLinux.yml@main
  windows-unit-tests:
    strategy:
      matrix:
        # node_version: [lts/-1, lts/*, latest]
        node_version: [lts/-1, lts/*]
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: salesforcecli/github-workflows/.github/actions/windowsCachePerf@main
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install  --network-timeout 600000
      - run: yarn build
      - run: yarn test
